name: Update-Dates

on:
  schedule:
  - cron: '01 0 1 * *'
  
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update dates
        run: |
          git config --global user.name 'Luvai Hassanali'
          git config --global user.email 'luvaihassanali@gmail.com'
          .\cv\UpdateDates.ps1
          git add .
          $commitMsg = "Update month " + (Get-Date).ToString("u")
          git commit -m $commitMsg
          git push -u origin main
